'use client';
import { useState, useEffect, type RefObject } from 'react';
import { Download, FolderOpen, Check, Loader2, X, AlertTriangle, Lock, Settings } from 'lucide-react';
import ClientSelector, { SelectedClient } from '@/components/ui/ClientSelector';
import { useModules } from '@/components/ui/ModulesProvider';
import { generatePdfBlob, downloadBlob, blobToBase64 } from '@/utils/pdfFromHtml';

type Status = 'idle' | 'generating' | 'uploading' | 'done' | 'error';

interface SaveReportModalProps {
  isOpen: boolean;
  /** Full HTML string for the report (used as fallback if paperRef is absent) */
  reportHtml: string;
  /** Ref to the live A4 paper div in the editor.  When present, the PDF is
   *  generated by cloning this element directly so the CSS is identical to
   *  the editor view, guaranteeing page-break alignment. */
  paperRef?: RefObject<HTMLElement | null>;
  /** Filename without extension — date suffix is added automatically */
  reportFileName: string;
  /** Feature identifier used for Drive folder organisation and vault tagging */
  feature: string;
  /** Vault document_type tag — defaults to 'report' */
  documentType?: string;
  initialClient?: SelectedClient | null;
  /** Optional: called after PDF download (and optional Drive upload) succeeds.
   *  Use for fire-and-forget side-effects like persisting a history record. */
  onAfterSave?: (ctx: { client: SelectedClient | null; clientCode: string }) => void;
  onClose: () => void;
}

export default function SaveReportModal({
  isOpen,
  reportHtml,
  paperRef,
  reportFileName,
  feature,
  documentType = 'report',
  initialClient,
  onAfterSave,
  onClose,
}: SaveReportModalProps) {
  const { isModuleActive } = useModules();
  const driveModuleActive = isModuleActive('google-drive');
  const vaultModuleActive = isModuleActive('document-vault');

  const [useDrive, setUseDrive] = useState(false);
  const [client, setClient] = useState<SelectedClient | null>(initialClient ?? null);
  const [clientCode, setClientCode] = useState(initialClient?.client_ref ?? '');
  const [status, setStatus] = useState<Status>('idle');
  const [statusLabel, setStatusLabel] = useState('');
  const [errorMsg, setErrorMsg] = useState('');
  const [driveCount, setDriveCount] = useState(0);

  useEffect(() => {
    if (isOpen) {
      setUseDrive(false);
      setClient(initialClient ?? null);
      setClientCode(initialClient?.client_ref ?? '');
      setStatus('idle');
      setStatusLabel('');
      setErrorMsg('');
      setDriveCount(0);
    }
  }, [isOpen, initialClient]);

  useEffect(() => {
    if (client?.client_ref) setClientCode(client.client_ref);
  }, [client]);

  if (!isOpen) return null;

  const dateStr = new Date().toISOString().slice(0, 10);
  const fullFileName = `${reportFileName}_${dateStr}`;
  const needsCode = useDrive && !clientCode.trim();
  const canSave = !useDrive || clientCode.trim().length > 0;
  const busy = status === 'generating' || status === 'uploading';

  const handleSave = async () => {
    setErrorMsg('');

    // Step 1 — generate PDF
    setStatus('generating');
    setStatusLabel('Generating PDF…');
    let pdfBlob: Blob;
    try {
      pdfBlob = await generatePdfBlob(reportHtml, paperRef);
    } catch (err) {
      setStatus('error');
      setErrorMsg(err instanceof Error ? err.message : 'PDF generation failed');
      return;
    }

    // Step 2 — upload to Drive (optional)
    if (useDrive) {
      setStatus('uploading');
      setStatusLabel('Uploading to Google Drive…');
      try {
        const base64 = await blobToBase64(pdfBlob);
        const res = await fetch('/api/documents/upload', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            files: [{ name: `${fullFileName}.pdf`, mimeType: 'application/pdf', base64 }],
            clientId: client?.id ?? null,
            clientCode: clientCode.trim(),
            feature,
          }),
        });
        if (!res.ok) {
          const e = await res.json();
          throw new Error(e.error || 'Drive upload failed');
        }
        const result = await res.json();
        const uploadedFiles: { name: string; driveUrl: string; driveFileId: string }[] = result.uploadedFiles ?? [];
        setDriveCount(uploadedFiles.length);

        if (vaultModuleActive && uploadedFiles.length > 0) {
          fetch('/api/vault/save-from-analysis', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              uploadedFiles: uploadedFiles.map(uf => ({
                ...uf,
                mimeType: 'application/pdf',
                fileSizeBytes: pdfBlob.size,
              })),
              transactions: [],
              clientId: client?.id ?? null,
              clientCode: clientCode.trim() || null,
              clientName: client?.name ?? null,
              sourceTool: feature,
              documentType,
            }),
          }).catch(err => console.error('[SaveReportModal] vault save failed:', err));
        }
      } catch (err) {
        setStatus('error');
        setErrorMsg(err instanceof Error ? err.message : 'Upload failed');
        return;
      }
    }

    // Step 3 — download locally
    downloadBlob(pdfBlob, `${fullFileName}.pdf`);
    // Optional side-effect (e.g. persist to outputs history)
    try { onAfterSave?.({ client, clientCode: clientCode.trim() }); } catch {/* swallow */}
    setStatus('done');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/50" onClick={!busy ? onClose : undefined} />

      <div className="relative glass-solid rounded-xl shadow-2xl w-full max-w-md mx-4 p-6 border border-[var(--border)]">

        {/* Header */}
        <div className="flex items-center justify-between mb-5">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-[var(--accent-light)] flex items-center justify-center shrink-0">
              <Download size={18} className="text-[var(--accent)]" />
            </div>
            <div>
              <h2 className="text-base font-semibold text-[var(--text-primary)]">Save Report</h2>
              <p className="text-sm text-[var(--text-muted)]">{fullFileName}.pdf</p>
            </div>
          </div>
          {!busy && status !== 'done' && (
            <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-[var(--bg-nav-hover)] text-[var(--text-muted)] transition-colors">
              <X size={16} />
            </button>
          )}
        </div>

        {/* Done */}
        {status === 'done' && (
          <div className="text-center py-4">
            <div className="w-12 h-12 rounded-full bg-emerald-100 dark:bg-emerald-900/30 flex items-center justify-center mx-auto mb-3">
              <Check size={22} className="text-emerald-600 dark:text-emerald-400" />
            </div>
            <p className="font-semibold text-[var(--text-primary)] mb-1">Report saved</p>
            <p className="text-sm text-[var(--text-muted)]">
              PDF downloaded
              {driveCount > 0 && <> · saved to Google Drive</>}
              {useDrive && driveCount === 0 && ' · Google Drive not connected'}
            </p>
            <button onClick={onClose} className="btn-primary mt-4 w-full">Done</button>
          </div>
        )}

        {/* Error */}
        {status === 'error' && (
          <div className="space-y-4">
            <div className="flex items-start gap-3 p-3 bg-red-50 dark:bg-red-900/10 border border-red-200 dark:border-red-800 rounded-xl">
              <AlertTriangle size={16} className="text-red-500 shrink-0 mt-0.5" />
              <p className="text-sm text-red-700 dark:text-red-400">{errorMsg}</p>
            </div>
            <div className="flex gap-3 justify-end">
              <button onClick={onClose} className="btn-secondary">Cancel</button>
              <button onClick={() => setStatus('idle')} className="btn-primary">Try again</button>
            </div>
          </div>
        )}

        {/* Loading */}
        {busy && (
          <div className="text-center py-6">
            <Loader2 size={28} className="animate-spin text-[var(--accent)] mx-auto mb-3" />
            <p className="font-medium text-[var(--text-primary)]">{statusLabel}</p>
            <p className="text-sm text-[var(--text-muted)] mt-1">
              {status === 'generating' ? 'This may take a few seconds' : 'Almost done'}
            </p>
          </div>
        )}

        {/* Idle form */}
        {status === 'idle' && (
          <div className="space-y-4">

            {/* Drive toggle */}
            {driveModuleActive ? (
              <div className="flex items-center justify-between p-4 bg-[var(--bg-nav-hover)] rounded-xl border border-[var(--border)]">
                <div>
                  <div className="flex items-center gap-2">
                    <FolderOpen size={15} className="text-[var(--text-secondary)]" />
                    <p className="text-sm font-medium text-[var(--text-primary)]">Save to Google Drive</p>
                  </div>
                  <p className="text-xs text-[var(--text-muted)] mt-0.5 ml-5">
                    {useDrive ? 'PDF will be saved to the client folder in Drive' : 'Toggle on to save a copy to Drive'}
                  </p>
                </div>
                <button
                  type="button"
                  onClick={() => setUseDrive(v => !v)}
                  className={`relative inline-flex h-6 w-11 rounded-full transition-colors shrink-0 ml-4 ${useDrive ? 'bg-[var(--accent)]' : 'bg-[var(--border-input)]'}`}
                >
                  <span className={`inline-block h-5 w-5 transform rounded-full bg-white shadow transition-transform mt-0.5 ml-0.5 ${useDrive ? 'translate-x-5' : 'translate-x-0'}`} />
                </button>
              </div>
            ) : (
              <div className="p-4 bg-[var(--bg-nav-hover)] rounded-xl border border-[var(--border)] opacity-60">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="flex items-center gap-2">
                      <FolderOpen size={15} className="text-[var(--text-muted)]" />
                      <p className="text-sm font-medium text-[var(--text-secondary)]">Save to Google Drive</p>
                      <Lock size={12} className="text-[var(--text-muted)]" />
                    </div>
                    <p className="text-xs text-[var(--text-muted)] mt-1 ml-5">
                      Unlock the Google Drive integration to save reports to Drive.
                    </p>
                  </div>
                  <div className="h-6 w-11 rounded-full bg-[var(--border-input)] shrink-0 ml-4 opacity-50" />
                </div>
                <a href="/settings?tab=modules" className="inline-flex items-center gap-1.5 mt-2 ml-5 text-xs text-[var(--accent)] hover:underline">
                  <Settings size={11} />
                  Ask your admin to enable it in Settings → Modules
                </a>
              </div>
            )}

            {/* Vault note */}
            {useDrive && driveModuleActive && !vaultModuleActive && (
              <div className="flex items-start gap-2 px-3 py-2 bg-amber-50 dark:bg-amber-900/10 border border-amber-200 dark:border-amber-800 rounded-lg">
                <AlertTriangle size={13} className="text-amber-500 shrink-0 mt-0.5" />
                <p className="text-xs text-amber-700 dark:text-amber-400">
                  PDF will be saved to Google Drive but won&apos;t be indexed in the Document Vault.{' '}
                  <a href="/settings?tab=modules" className="underline font-medium">Enable the Document Vault module</a> to index it automatically.
                </p>
              </div>
            )}

            {useDrive && driveModuleActive && vaultModuleActive && (
              <div className="flex items-center gap-2 px-3 py-2 bg-[var(--accent-light)] rounded-lg text-xs text-[var(--accent)] font-medium">
                <Check size={12} />
                PDF will be saved to Drive and indexed in the Document Vault
              </div>
            )}

            {/* Client selector when Drive on */}
            {useDrive && driveModuleActive && (
              <div className="space-y-3">
                <div>
                  <label className="block text-xs font-semibold text-[var(--text-muted)] uppercase tracking-wide mb-1.5">
                    Client <span className="text-red-500">*</span>
                  </label>
                  <ClientSelector value={client} onSelect={c => { setClient(c); if (c?.client_ref) setClientCode(c.client_ref); }} />
                </div>
                {(!client?.client_ref || !client) && (
                  <div>
                    <label className="block text-xs font-semibold text-[var(--text-muted)] uppercase tracking-wide mb-1.5">
                      Client code <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="text"
                      value={clientCode}
                      onChange={e => setClientCode(e.target.value.toUpperCase())}
                      placeholder="e.g. MM001"
                      className={`input-base w-full font-mono ${needsCode ? 'border-amber-400 dark:border-amber-500 bg-amber-50 dark:bg-amber-900/10' : ''}`}
                    />
                    {needsCode && (
                      <p className="text-xs text-amber-600 dark:text-amber-400 mt-1.5 flex items-center gap-1">
                        <AlertTriangle size={12} className="shrink-0" />
                        A client code is required to organise files in Drive
                      </p>
                    )}
                  </div>
                )}
                {clientCode.trim() && (
                  <p className="text-xs text-[var(--text-muted)]">
                    Files will be saved to:{' '}
                    <span className="font-mono font-medium text-[var(--text-primary)]">SMITH Files / {clientCode.trim()}</span>
                  </p>
                )}
              </div>
            )}

            {/* File summary */}
            <div className="p-3 bg-[var(--bg-nav-hover)] rounded-xl border border-[var(--border)]">
              <div className="flex items-center gap-2 mb-1">
                <Download size={13} className="text-[var(--text-secondary)]" />
                <span className="text-xs font-semibold text-[var(--text-secondary)] uppercase tracking-wide">PDF Download</span>
              </div>
              <p className="text-sm text-[var(--text-primary)]">{fullFileName}.pdf</p>
            </div>

            <div className="flex gap-3 justify-end pt-1">
              <button onClick={onClose} className="btn-secondary">Cancel</button>
              <button
                onClick={handleSave}
                disabled={!canSave}
                className="btn-primary disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {useDrive && driveModuleActive ? (
                  <><FolderOpen size={14} /> Save & Download PDF</>
                ) : (
                  <><Download size={14} /> Download PDF</>
                )}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
