import type { DefaultTemplate } from '@/types';

const X  = 220;  // centre column x for main flow steps
const XR = 510;  // right column x for reminder/chaser steps
const Y  = 200;  // vertical step spacing

// Explicit handle shortcuts so React Flow routes correctly regardless of declaration order.
// VD = vertical down (main flow), TO = timeout right to chaser, BK = back-left from chaser.
const VD = { source_handle: 'h-bot',   target_handle: 'h-top'  } as const;
const TO = { source_handle: 'h-right', target_handle: 'h-top'  } as const;
const BK = { source_handle: 'h-left',  target_handle: 'h-top'  } as const;

// Start / End shared defaults
const START_CFG = (type: 'manual' | 'deadline_relative' | 'day_of_month', opts?: object) => ({
  step_type: 'start' as const,
  assignee_role: 'any' as const,
  email_reminder_enabled: false,
  email_reminder_config: { recipients: [] as const, timing: 'on_assign' as const },
  start_trigger_config: { type, ...opts },
  end_config: null,
});
const END_CFG = {
  step_type: 'end' as const,
  assignee_role: 'any' as const,
  email_reminder_enabled: false,
  email_reminder_config: { recipients: [] as const, timing: 'on_assign' as const },
  start_trigger_config: null,
  end_config: { send_completion_notification: true, notification_recipients: ['assignee'] as const },
};

export const DEFAULT_TASK_TEMPLATES: DefaultTemplate[] = [

  // ─── VAT Return ──────────────────────────────────────────────────────────────
  {
    id: 'default-vat-return',
    name: 'VAT Return',
    description: 'Full VAT return workflow from document collection through HMRC submission.',
    category: 'vat',
    recurrence_type: 'quarterly',
    estimated_duration_days: 14,
    steps: [
      { step_key: 'start', title: 'Start', ...START_CFG('deadline_relative', { months_before: 2, deadline_unit: 'months', deadline_label: 'VAT deadline' }), position_x: X, position_y: 0 },
      { step_key: 's1',  title: 'Request documents from client',    description: 'Ask the client to provide bank statements, invoices and receipts for the VAT period.', assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X,  position_y: Y * 1 },
      { step_key: 's2',  title: 'Client provides documents',        description: 'Wait for the client to send all relevant documents for the VAT period.',                assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, client_instructions: 'Please send your bank statements, invoices and receipts for this VAT period.', position_x: X,  position_y: Y * 2 },
      { step_key: 'sr1', title: 'Send document chaser to client',   description: 'Client has not yet provided documents — send a polite chaser email.',                   assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 2 },
      { step_key: 's3',  title: 'Process bank statements',          description: 'Extract transactions from bank statements using the Bank to CSV tool.',                 assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 30, position_x: X,  position_y: Y * 3, tool_module_id: 'bank-to-csv' },
      { step_key: 's4',  title: 'Analyse invoices & receipts',      description: 'Code all invoices and receipts to the correct accounts using Full Analysis.',           assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 60, position_x: X,  position_y: Y * 4, tool_module_id: 'full-analysis' },
      { step_key: 's5',  title: 'Prepare VAT return',               description: 'Reconcile VAT figures and prepare the return.',                                         assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 45, position_x: X,  position_y: Y * 5 },
      { step_key: 's6',  title: 'Manager review',                   description: 'Senior staff member reviews the VAT return before client sign-off.',                   assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 30, position_x: X,  position_y: Y * 6 },
      { step_key: 's7',  title: 'Send to client for approval',      description: 'Send the prepared VAT return to the client for review and approval.',                   assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X,  position_y: Y * 7 },
      { step_key: 's8',  title: 'Client approves return',           description: 'Wait for the client to review and approve the VAT return figures.',                     assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, client_instructions: 'Please review the VAT return figures and confirm approval.', position_x: X, position_y: Y * 8 },
      { step_key: 'sr2', title: 'Send approval reminder to client', description: 'Client has not yet approved the VAT return — send a reminder.',                        assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 8 },
      { step_key: 's9',  title: 'Submit to HMRC',                   description: 'Submit the approved VAT return to HMRC via Making Tax Digital.',                       assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 20, position_x: X,  position_y: Y * 9 },
      { step_key: 's10', title: 'Advise client of payment due',     description: 'Email the client to confirm submission and advise any VAT payment amount and due date.', assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 10, position_x: X,  position_y: Y * 10 },
      { step_key: 'end', title: 'Complete', ...END_CFG, position_x: X, position_y: Y * 11 },
    ],
    edges: [
      { from_step_key: 'start', to_step_key: 's1',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's2',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 3 }, ...TO },
      { from_step_key: 'sr1', to_step_key: 's2',  condition_type: 'always',      ...BK },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's4',  to_step_key: 's5',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's5',  to_step_key: 's6',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's6',  to_step_key: 's7',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's7',  to_step_key: 's8',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's8',  to_step_key: 'sr2', condition_type: 'timeout',     condition_config: { timeout_days: 5 }, ...TO },
      { from_step_key: 'sr2', to_step_key: 's8',  condition_type: 'always',      ...BK },
      { from_step_key: 's8',  to_step_key: 's9',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's9',  to_step_key: 's10', condition_type: 'on_complete', ...VD },
      { from_step_key: 's10', to_step_key: 'end', condition_type: 'on_complete', ...VD },
    ],
  },

  // ─── Year End Accounts (Limited Company) ────────────────────────────────────
  {
    id: 'default-year-end-ltd',
    name: 'Year End Accounts (Ltd)',
    description: 'Full year-end workflow for limited companies including HMRC and Companies House filing.',
    category: 'year_end',
    recurrence_type: 'annually',
    estimated_duration_days: 30,
    steps: [
      { step_key: 'start', title: 'Start', ...START_CFG('deadline_relative', { months_before: 3, deadline_unit: 'months', deadline_label: 'year end' }), position_x: X, position_y: 0 },
      { step_key: 's1',  title: 'Request year-end documents',        description: 'Request bank statements, invoices, payroll records and any other relevant documents from the client.', assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 20,  position_x: X,  position_y: Y * 1 },
      { step_key: 's2',  title: 'Client provides all documents',     description: 'Wait for the client to send all year-end documents.',                                                   assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, client_instructions: 'Please send all year-end documents including bank statements, invoices, receipts and payroll records.',  position_x: X,  position_y: Y * 2 },
      { step_key: 'sr1', title: 'Send document chaser to client',    description: 'Client has not yet provided year-end documents — send a chaser email.',                                  assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,   position_x: XR, position_y: Y * 2 },
      { step_key: 's3',  title: 'Process bank statements',           description: 'Extract all bank transactions using the Bank to CSV tool.',                                              assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 45,  position_x: X,  position_y: Y * 3, tool_module_id: 'bank-to-csv' },
      { step_key: 's4',  title: 'Analyse invoices & receipts',       description: 'Code all invoices and receipts using the Full Analysis tool.',                                           assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 90,  position_x: X,  position_y: Y * 4, tool_module_id: 'full-analysis' },
      { step_key: 's5',  title: 'Prepare draft accounts',            description: 'Draft the statutory accounts and tax computation.',                                                      assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 120, position_x: X,  position_y: Y * 5, tool_module_id: 'final-accounts' },
      { step_key: 's6',  title: 'Manager review',                    description: 'Senior staff member reviews the accounts and tax computation.',                                          assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 60,  position_x: X,  position_y: Y * 6 },
      { step_key: 's7',  title: 'Send draft to client',              description: 'Send the draft accounts to the client for director review.',                                             assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15,  position_x: X,  position_y: Y * 7 },
      { step_key: 's8',  title: 'Director approval',                 description: 'Wait for the client/director to review and approve the draft accounts.',                                 assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, client_instructions: 'Please review the draft accounts and confirm your approval as director.',  position_x: X,  position_y: Y * 8 },
      { step_key: 'sr2', title: 'Send approval reminder to client',  description: 'Client has not yet approved the draft accounts — send a reminder.',                                     assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,   position_x: XR, position_y: Y * 8 },
      { step_key: 's9',  title: 'File accounts with Companies House',description: 'File the approved accounts with Companies House.',                                                       assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 30,  position_x: X,  position_y: Y * 9 },
      { step_key: 's10', title: 'File CT600 with HMRC',              description: 'Submit the corporation tax return (CT600) to HMRC.',                                                    assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 30,  position_x: X,  position_y: Y * 10 },
      { step_key: 's11', title: 'Invoice client & close job',        description: 'Issue the invoice to the client and mark the job as complete.',                                          assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 15,  position_x: X,  position_y: Y * 11 },
      { step_key: 'end', title: 'Complete', ...END_CFG, position_x: X, position_y: Y * 12 },
    ],
    edges: [
      { from_step_key: 'start', to_step_key: 's1',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's2',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 5 }, ...TO },
      { from_step_key: 'sr1', to_step_key: 's2',  condition_type: 'always',      ...BK },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's4',  to_step_key: 's5',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's5',  to_step_key: 's6',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's6',  to_step_key: 's7',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's7',  to_step_key: 's8',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's8',  to_step_key: 'sr2', condition_type: 'timeout',     condition_config: { timeout_days: 7 }, ...TO },
      { from_step_key: 'sr2', to_step_key: 's8',  condition_type: 'always',      ...BK },
      { from_step_key: 's8',  to_step_key: 's9',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's9',  to_step_key: 's10', condition_type: 'on_complete', ...VD },
      { from_step_key: 's10', to_step_key: 's11', condition_type: 'on_complete', ...VD },
      { from_step_key: 's11', to_step_key: 'end', condition_type: 'on_complete', ...VD },
    ],
  },

  // ─── Year End Accounts (Sole Trader) ────────────────────────────────────────
  {
    id: 'default-year-end-sole-trader',
    name: 'Year End Accounts (Sole Trader)',
    description: 'Year-end workflow for sole traders including SA supplementary pages.',
    category: 'year_end',
    recurrence_type: 'annually',
    estimated_duration_days: 21,
    steps: [
      { step_key: 'start', title: 'Start', ...START_CFG('deadline_relative', { months_before: 3, deadline_unit: 'months', deadline_label: 'year end' }), position_x: X, position_y: 0 },
      { step_key: 's1',  title: 'Request year-end documents',          description: 'Ask the client for bank statements, invoices, receipts and any other income or expense records.', assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 20, position_x: X,  position_y: Y * 1 },
      { step_key: 's2',  title: 'Client provides documents',           description: 'Wait for the client to send all year-end documents.',                                              assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, client_instructions: 'Please send your bank statements, invoices and any income or expense records for the year.',  position_x: X,  position_y: Y * 2 },
      { step_key: 'sr1', title: 'Send document chaser to client',      description: 'Client has not yet provided year-end documents — send a chaser email.',                            assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 2 },
      { step_key: 's3',  title: 'Process bank statements',             description: 'Extract transactions from bank statements using the Bank to CSV tool.',                            assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 45, position_x: X,  position_y: Y * 3, tool_module_id: 'bank-to-csv' },
      { step_key: 's4',  title: 'Analyse invoices & receipts',         description: 'Code all invoices and receipts to the correct accounts using Full Analysis.',                      assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 90, position_x: X,  position_y: Y * 4, tool_module_id: 'full-analysis' },
      { step_key: 's5',  title: 'Prepare accounts & SA supplementary', description: 'Prepare the year-end accounts and self assessment supplementary pages.',                          assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 90, position_x: X,  position_y: Y * 5, tool_module_id: 'final-accounts' },
      { step_key: 's6',  title: 'Manager review',                      description: 'Senior staff member reviews the accounts and SA supplementary pages.',                             assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 45, position_x: X,  position_y: Y * 6 },
      { step_key: 's7',  title: 'Send to client for approval',         description: 'Send the draft accounts and tax return to the client for approval.',                               assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X,  position_y: Y * 7 },
      { step_key: 's8',  title: 'Client approves accounts',            description: 'Wait for the client to review and approve the accounts and tax return.',                           assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, client_instructions: 'Please review and approve your year-end accounts and self assessment return.',  position_x: X,  position_y: Y * 8 },
      { step_key: 'sr2', title: 'Send approval reminder to client',    description: 'Client has not yet approved the accounts — send a reminder.',                                      assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 8 },
      { step_key: 's9',  title: 'File self assessment return',         description: 'Submit the self assessment return to HMRC.',                                                       assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 30, position_x: X,  position_y: Y * 9 },
      { step_key: 's10', title: 'Advise tax payment dates',            description: 'Email the client to confirm submission and advise tax payment amounts and deadlines.',             assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X,  position_y: Y * 10 },
      { step_key: 'end', title: 'Complete', ...END_CFG, position_x: X, position_y: Y * 11 },
    ],
    edges: [
      { from_step_key: 'start', to_step_key: 's1',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's2',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 5 }, ...TO },
      { from_step_key: 'sr1', to_step_key: 's2',  condition_type: 'always',      ...BK },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's4',  to_step_key: 's5',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's5',  to_step_key: 's6',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's6',  to_step_key: 's7',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's7',  to_step_key: 's8',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's8',  to_step_key: 'sr2', condition_type: 'timeout',     condition_config: { timeout_days: 5 }, ...TO },
      { from_step_key: 'sr2', to_step_key: 's8',  condition_type: 'always',      ...BK },
      { from_step_key: 's8',  to_step_key: 's9',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's9',  to_step_key: 's10', condition_type: 'on_complete', ...VD },
      { from_step_key: 's10', to_step_key: 'end', condition_type: 'on_complete', ...VD },
    ],
  },

  // ─── Self Assessment ─────────────────────────────────────────────────────────
  {
    id: 'default-self-assessment',
    name: 'Self Assessment Return',
    description: 'Individual self assessment tax return workflow.',
    category: 'self_assessment',
    recurrence_type: 'annually',
    estimated_duration_days: 21,
    steps: [
      { step_key: 'start', title: 'Start', ...START_CFG('deadline_relative', { months_before: 3, deadline_unit: 'months', deadline_label: '31 January deadline' }), position_x: X, position_y: 0 },
      { step_key: 's1',  title: 'Request personal income information', description: 'Employment income, dividends, interest, rental income, capital gains etc.', assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X,  position_y: Y * 1 },
      { step_key: 's2',  title: 'Client provides all income details',  description: 'Wait for the client to supply all income and expense information.',          assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, client_instructions: 'Please provide details of all your income for the year — employment, self-employment, dividends, interest, rental income and any capital gains.', position_x: X,  position_y: Y * 2 },
      { step_key: 'sr1', title: 'Send income information chaser',      description: 'Client has not yet provided their income details — send a chaser email.',    assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 2 },
      { step_key: 's3',  title: 'Process rental income & expenses',    description: 'If the client has rental properties, use the Landlord tool to process rental income and expenses.', assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 60, position_x: X, position_y: Y * 3, tool_module_id: 'landlord' },
      { step_key: 's4',  title: 'Prepare SA return',                   description: 'Complete the self assessment return with all income sources and reliefs.',   assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 90, position_x: X,  position_y: Y * 4 },
      { step_key: 's5',  title: 'Manager review',                      description: 'Senior staff member reviews the SA return for accuracy.',                    assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 30, position_x: X,  position_y: Y * 5 },
      { step_key: 's6',  title: 'Send to client for approval',         description: 'Send the SA return to the client for review and approval before submission.', assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 6 },
      { step_key: 's7',  title: 'Client approves return',              description: 'Wait for the client to review and approve the SA return.',                   assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, client_instructions: 'Please review your self assessment return and confirm your approval for submission.', position_x: X,  position_y: Y * 7 },
      { step_key: 'sr2', title: 'Send approval reminder to client',    description: 'Client has not yet approved the SA return — send a reminder.',               assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 7 },
      { step_key: 's8',  title: 'Submit to HMRC',                      description: 'Submit the approved self assessment return to HMRC.',                        assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 20, position_x: X,  position_y: Y * 8 },
      { step_key: 's9',  title: 'Advise tax payment dates to client',  description: 'Email the client to confirm submission and advise tax payment amounts and dates.', assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 9 },
      { step_key: 'end', title: 'Complete', ...END_CFG, position_x: X, position_y: Y * 10 },
    ],
    edges: [
      { from_step_key: 'start', to_step_key: 's1',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's2',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 5 }, ...TO },
      { from_step_key: 'sr1', to_step_key: 's2',  condition_type: 'always',      ...BK },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's4',  to_step_key: 's5',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's5',  to_step_key: 's6',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's6',  to_step_key: 's7',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's7',  to_step_key: 'sr2', condition_type: 'timeout',     condition_config: { timeout_days: 5 }, ...TO },
      { from_step_key: 'sr2', to_step_key: 's7',  condition_type: 'always',      ...BK },
      { from_step_key: 's7',  to_step_key: 's8',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's8',  to_step_key: 's9',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's9',  to_step_key: 'end', condition_type: 'on_complete', ...VD },
    ],
  },

  // ─── Monthly Payroll ─────────────────────────────────────────────────────────
  {
    id: 'default-payroll-monthly',
    name: 'Payroll Run (Monthly)',
    description: 'Monthly payroll processing and RTI submission workflow.',
    category: 'payroll',
    recurrence_type: 'monthly',
    estimated_duration_days: 5,
    steps: [
      { step_key: 'start', title: 'Start', ...START_CFG('day_of_month', { day_of_month: 20 }), position_x: X, position_y: 0 },
      { step_key: 's0',  title: 'Request payroll information from client', description: 'Request hours, new starters, leavers, salary changes and bonuses for the month.', assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 10, position_x: X,  position_y: Y * 1 },
      { step_key: 's1',  title: 'Receive payroll information from client', description: 'Wait for the client to provide all payroll information.',                          assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, client_instructions: 'Please provide payroll details including hours worked, any salary changes, new starters, leavers and any bonuses.', position_x: X,  position_y: Y * 2 },
      { step_key: 'sr1', title: 'Send payroll information chaser',         description: 'Client has not yet provided payroll information — send an urgent chaser.',         assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 2 },
      { step_key: 's2',  title: 'Process payroll',                         description: 'Process the payroll for all employees for this month.',                            assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 60, position_x: X, position_y: Y * 3 },
      { step_key: 's3',  title: 'Prepare P32 summary',                     description: 'Generate and check the P32 employer payment record.',                             assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 4, tool_module_id: 'p32' },
      { step_key: 's4',  title: 'Submit RTI to HMRC',                      description: 'Submit the Full Payment Submission (FPS) to HMRC via RTI.',                       assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 5 },
      { step_key: 's5',  title: 'Send payslips & P32 to client',           description: 'Email payslips to employees and the P32 summary to the client.',                  assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 6 },
      { step_key: 'end', title: 'Complete', ...END_CFG, position_x: X, position_y: Y * 7 },
    ],
    edges: [
      { from_step_key: 'start', to_step_key: 's0',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's0',  to_step_key: 's1',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's1',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 2 }, ...TO },
      { from_step_key: 'sr1', to_step_key: 's1',  condition_type: 'always',      ...BK },
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's4',  to_step_key: 's5',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's5',  to_step_key: 'end', condition_type: 'on_complete', ...VD },
    ],
  },

  // ─── Bi-weekly Payroll ───────────────────────────────────────────────────────
  {
    id: 'default-payroll-biweekly',
    name: 'Payroll Run (Bi-weekly)',
    description: 'Bi-weekly payroll processing for clients on a fortnightly pay schedule.',
    category: 'payroll',
    recurrence_type: 'bi-weekly',
    estimated_duration_days: 3,
    steps: [
      { step_key: 'start', title: 'Start', ...START_CFG('manual'), position_x: X, position_y: 0 },
      { step_key: 's0',  title: 'Request payroll information from client', description: 'Request hours, any changes or new starters for this fortnight.',                  assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 10, position_x: X,  position_y: Y * 1 },
      { step_key: 's1',  title: 'Receive payroll information from client', description: 'Wait for the client to provide all payroll information for this pay period.',     assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, client_instructions: 'Please provide hours worked and any changes (new starters, leavers, salary changes) for this fortnight.', position_x: X,  position_y: Y * 2 },
      { step_key: 'sr1', title: 'Send payroll information chaser',         description: 'Client has not yet provided payroll information — send an urgent chaser.',        assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 2 },
      { step_key: 's2',  title: 'Process payroll',                         description: 'Process the fortnightly payroll for all employees.',                              assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 45, position_x: X, position_y: Y * 3 },
      { step_key: 's3',  title: 'Submit RTI to HMRC',                      description: 'Submit the Full Payment Submission (FPS) to HMRC via RTI.',                      assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 4 },
      { step_key: 's4',  title: 'Send payslips to client',                 description: 'Email payslips to employees and notify the client.',                              assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 10, position_x: X, position_y: Y * 5 },
      { step_key: 'end', title: 'Complete', ...END_CFG, position_x: X, position_y: Y * 6 },
    ],
    edges: [
      { from_step_key: 'start', to_step_key: 's0',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's0',  to_step_key: 's1',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's1',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 1 }, ...TO },
      { from_step_key: 'sr1', to_step_key: 's1',  condition_type: 'always',      ...BK },
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's4',  to_step_key: 'end', condition_type: 'on_complete', ...VD },
    ],
  },

  // ─── Confirmation Statement ──────────────────────────────────────────────────
  {
    id: 'default-confirmation-statement',
    name: 'Confirmation Statement',
    description: 'Annual Companies House confirmation statement filing workflow.',
    category: 'companies_house',
    recurrence_type: 'annually',
    estimated_duration_days: 7,
    steps: [
      { step_key: 'start', title: 'Start', ...START_CFG('deadline_relative', { weeks_before: 6, deadline_unit: 'weeks', deadline_label: 'confirmation statement due date' }), position_x: X, position_y: 0 },
      { step_key: 's1',  title: 'Check Companies House data',           description: 'Review current officer, PSC, and share capital information on Companies House.',  assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 20, position_x: X,  position_y: Y * 1, tool_module_id: 'ch-secretarial' },
      { step_key: 's2',  title: 'Confirm details with client',          description: 'Email client to confirm all Companies House details are still correct.',            assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X,  position_y: Y * 2 },
      { step_key: 's3',  title: 'Client confirms all details correct',  description: 'Wait for the client to confirm their Companies House details are accurate.',        assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, client_instructions: 'Please confirm that all information held at Companies House is still correct — officers, addresses, share capital and persons with significant control.', position_x: X,  position_y: Y * 3 },
      { step_key: 'sr1', title: 'Send confirmation reminder to client', description: 'Client has not yet confirmed their Companies House details — send a chaser.',       assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 3 },
      { step_key: 's4',  title: 'File confirmation statement',          description: 'File the confirmation statement with Companies House.',                              assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 20, position_x: X,  position_y: Y * 4 },
      { step_key: 's5',  title: 'Advise client filing complete',        description: 'Email the client to confirm the confirmation statement has been filed.',             assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 10, position_x: X,  position_y: Y * 5 },
      { step_key: 'end', title: 'Complete', ...END_CFG, position_x: X, position_y: Y * 6 },
    ],
    edges: [
      { from_step_key: 'start', to_step_key: 's1',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's3',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 3 }, ...TO },
      { from_step_key: 'sr1', to_step_key: 's3',  condition_type: 'always',      ...BK },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's4',  to_step_key: 's5',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's5',  to_step_key: 'end', condition_type: 'on_complete', ...VD },
    ],
  },

  // ─── Bookkeeping Review ──────────────────────────────────────────────────────
  {
    id: 'default-bookkeeping-review',
    name: 'Bookkeeping Review',
    description: 'Periodic bookkeeping review — suitable for monthly or quarterly management accounts clients.',
    category: 'bookkeeping',
    recurrence_type: 'monthly',
    estimated_duration_days: 7,
    steps: [
      { step_key: 'start', title: 'Start', ...START_CFG('day_of_month', { day_of_month: 1 }), position_x: X, position_y: 0 },
      { step_key: 's1',  title: 'Request documents from client',    description: 'Email the client to request bank statements, invoices and receipts for the period.', assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X,  position_y: Y * 1 },
      { step_key: 's2',  title: 'Client provides documents',        description: 'Wait for the client to send all relevant documents.',                               assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, client_instructions: 'Please send your bank statements, invoices and receipts for the period.', position_x: X,  position_y: Y * 2 },
      { step_key: 'sr1', title: 'Send document chaser to client',   description: 'Client has not yet provided their documents — send a chaser email.',                assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 2 },
      { step_key: 's3',  title: 'Process bank statements',          description: 'Extract all transactions from bank statements using the Bank to CSV tool.',         assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 30, position_x: X, position_y: Y * 3, tool_module_id: 'bank-to-csv' },
      { step_key: 's4',  title: 'Analyse invoices & receipts',      description: 'Code all invoices and receipts to the correct accounts using Full Analysis.',       assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 60, position_x: X, position_y: Y * 4, tool_module_id: 'full-analysis' },
      { step_key: 's5',  title: 'Reconcile accounts',               description: 'Reconcile all accounts and ensure the trial balance is clean.',                     assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 30, position_x: X, position_y: Y * 5 },
      { step_key: 's6',  title: 'Prepare management accounts',      description: 'Produce the management accounts and performance report.',                           assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 45, position_x: X, position_y: Y * 6, tool_module_id: 'performance' },
      { step_key: 's7',  title: 'Manager review',                   description: 'Senior staff member reviews the management accounts before sending to client.',     assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 30, position_x: X, position_y: Y * 7 },
      { step_key: 's8',  title: 'Send report to client',            description: 'Email the management accounts and performance report to the client.',                assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 8 },
      { step_key: 'end', title: 'Complete', ...END_CFG, position_x: X, position_y: Y * 9 },
    ],
    edges: [
      { from_step_key: 'start', to_step_key: 's1',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's2',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 3 }, ...TO },
      { from_step_key: 'sr1', to_step_key: 's2',  condition_type: 'always',      ...BK },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's4',  to_step_key: 's5',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's5',  to_step_key: 's6',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's6',  to_step_key: 's7',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's7',  to_step_key: 's8',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's8',  to_step_key: 'end', condition_type: 'on_complete', ...VD },
    ],
  },
];

export const TEMPLATE_CATEGORY_LABELS: Record<string, string> = {
  vat: 'VAT',
  year_end: 'Year End',
  self_assessment: 'Self Assessment',
  payroll: 'Payroll',
  companies_house: 'Companies House',
  bookkeeping: 'Bookkeeping',
  cis: 'CIS',
  internal: 'Internal',
  onboarding: 'Onboarding',
  performance: 'Performance',
  management: 'Management',
  audit: 'Audit',
  general: 'General',
  other: 'Other',
};
