import type { DefaultTemplate } from '@/types';

const X  = 220;  // centre column x for main flow steps
const XR = 510;  // right column x for reminder/chaser steps
const Y  = 200;  // vertical step spacing

// Explicit handle shortcuts so React Flow routes correctly regardless of declaration order.
// VD = vertical down (main flow), TO = timeout right to chaser, BK = back-left from chaser.
const VD = { source_handle: 'h-bot',   target_handle: 'h-top'  } as const;
const TO = { source_handle: 'h-right', target_handle: 'h-top'  } as const;
const BK = { source_handle: 'h-left',  target_handle: 'h-top'  } as const;

export const DEFAULT_TASK_TEMPLATES: DefaultTemplate[] = [

  // ─── VAT Return ──────────────────────────────────────────────────────────────
  {
    id: 'default-vat-return',
    name: 'VAT Return',
    description: 'Full VAT return workflow from document collection through HMRC submission.',
    category: 'vat',
    recurrence_type: 'quarterly',
    estimated_duration_days: 14,
    steps: [
      { step_key: 's1',  title: 'Request documents from client',   description: 'Ask the client to provide bank statements, invoices and receipts for the period.', assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X,  position_y: 0 },
      { step_key: 'sr1', title: 'Send document chaser to client',  description: 'Client has not yet provided documents — send a polite chaser email.',             assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 1 },
      { step_key: 's2',  title: 'Client provides documents',       description: 'Wait for the client to send all relevant documents.',                               assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' },                             position_x: X,  position_y: Y * 2 },
      { step_key: 's3',  title: 'Process bank statements',         description: 'Extract transactions from bank statements.',                                        assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 30, position_x: X,  position_y: Y * 3 },
      { step_key: 's4',  title: 'Analyse invoices & receipts',     description: 'Code all invoices and receipts to the correct accounts.',                           assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 60, position_x: X,  position_y: Y * 4, tool_module_id: 'full-analysis' },
      { step_key: 's5',  title: 'Prepare VAT return',              description: 'Reconcile VAT and prepare the return figures.',                                     assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 45, position_x: X,  position_y: Y * 5 },
      { step_key: 's6',  title: 'Manager review',                  description: 'Senior staff member reviews the return before client sign-off.',                    assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 30, position_x: X,  position_y: Y * 6 },
      { step_key: 's7',  title: 'Send to client for approval',                                                                                                       assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X,  position_y: Y * 7 },
      { step_key: 'sr2', title: 'Send approval reminder to client', description: 'Client has not yet approved the VAT return — send a reminder.',                    assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 8 },
      { step_key: 's8',  title: 'Client approves return',                                                                                                            assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' },                             position_x: X,  position_y: Y * 9 },
      { step_key: 's9',  title: 'Submit to HMRC',                                                                                                                   assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 20, position_x: X,  position_y: Y * 10 },
      { step_key: 's10', title: 'Advise client of payment due',                                                                                                      assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 10, position_x: X,  position_y: Y * 11 },
    ],
    edges: [
      { from_step_key: 's1',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 3 }, ...TO },
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 'sr1', to_step_key: 's2',  condition_type: 'always',      ...BK },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's4',  to_step_key: 's5',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's5',  to_step_key: 's6',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's6',  to_step_key: 's7',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's7',  to_step_key: 'sr2', condition_type: 'timeout',     condition_config: { timeout_days: 5 }, ...TO },
      { from_step_key: 's7',  to_step_key: 's8',  condition_type: 'on_complete', ...VD },
      { from_step_key: 'sr2', to_step_key: 's8',  condition_type: 'always',      ...BK },
      { from_step_key: 's8',  to_step_key: 's9',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's9',  to_step_key: 's10', condition_type: 'on_complete', ...VD },
    ],
  },

  // ─── Year End Accounts (Limited Company) ────────────────────────────────────
  {
    id: 'default-year-end-ltd',
    name: 'Year End Accounts (Ltd)',
    description: 'Full year-end workflow for limited companies including HMRC and Companies House filing.',
    category: 'year_end',
    recurrence_type: 'annually',
    estimated_duration_days: 30,
    steps: [
      { step_key: 's1',  title: 'Request year-end documents',        description: 'Request bank statements, invoices, payroll records and any other relevant documents.', assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 20, position_x: X,  position_y: 0 },
      { step_key: 'sr1', title: 'Send document chaser to client',     description: 'Client has not yet provided year-end documents — send a chaser email.',               assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 1 },
      { step_key: 's2',  title: 'Client provides all documents',                                                                                                            assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' },                             position_x: X,  position_y: Y * 2 },
      { step_key: 's3',  title: 'Process bank statements',                                                                                                                  assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 45, position_x: X,  position_y: Y * 3, tool_module_id: 'bank-to-csv' },
      { step_key: 's4',  title: 'Analyse invoices & receipts',                                                                                                              assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 90, position_x: X,  position_y: Y * 4, tool_module_id: 'full-analysis' },
      { step_key: 's5',  title: 'Prepare draft accounts',                                                                                                                   assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 120, position_x: X, position_y: Y * 5, tool_module_id: 'final-accounts' },
      { step_key: 's6',  title: 'Manager review',                                                                                                                          assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 60, position_x: X,  position_y: Y * 6 },
      { step_key: 's7',  title: 'Send draft to client',                                                                                                                    assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X,  position_y: Y * 7 },
      { step_key: 'sr2', title: 'Send approval reminder to client',   description: 'Client has not yet reviewed the draft accounts — send a reminder.',                   assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 8 },
      { step_key: 's8',  title: 'Director approval meeting',                                                                                                               assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 60, position_x: X,  position_y: Y * 9 },
      { step_key: 's9',  title: 'File accounts with Companies House',                                                                                                      assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 30, position_x: 80, position_y: Y * 10 },
      { step_key: 's10', title: 'File CT600 with HMRC',                                                                                                                    assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 30, position_x: 360, position_y: Y * 10 },
      { step_key: 's11', title: 'Invoice client & close job',                                                                                                              assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X,  position_y: Y * 11 },
    ],
    edges: [
      { from_step_key: 's1',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 5 }, ...TO },
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 'sr1', to_step_key: 's2',  condition_type: 'always',      ...BK },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's4',  to_step_key: 's5',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's5',  to_step_key: 's6',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's6',  to_step_key: 's7',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's7',  to_step_key: 'sr2', condition_type: 'timeout',     condition_config: { timeout_days: 7 }, ...TO },
      { from_step_key: 's7',  to_step_key: 's8',  condition_type: 'on_complete', ...VD },
      { from_step_key: 'sr2', to_step_key: 's8',  condition_type: 'always',      ...BK },
      { from_step_key: 's8',  to_step_key: 's9',  label: 'Parallel', condition_type: 'on_complete', ...VD },
      { from_step_key: 's8',  to_step_key: 's10', label: 'Parallel', condition_type: 'on_complete', ...VD },
      { from_step_key: 's9',  to_step_key: 's11', condition_type: 'on_complete', ...VD },
      { from_step_key: 's10', to_step_key: 's11', condition_type: 'on_complete', ...VD },
    ],
  },

  // ─── Year End Accounts (Sole Trader) ────────────────────────────────────────
  {
    id: 'default-year-end-sole-trader',
    name: 'Year End Accounts (Sole Trader)',
    description: 'Year-end workflow for sole traders including SA supplementary pages.',
    category: 'year_end',
    recurrence_type: 'annually',
    estimated_duration_days: 21,
    steps: [
      { step_key: 's1',  title: 'Request year-end documents',       assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 20, position_x: X,  position_y: 0 },
      { step_key: 'sr1', title: 'Send document chaser to client',   description: 'Client has not yet provided year-end documents — send a chaser email.',    assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 1 },
      { step_key: 's2',  title: 'Client provides documents',                                                                                                  assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' },                             position_x: X,  position_y: Y * 2 },
      { step_key: 's3',  title: 'Process bank statements',          assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 45,  position_x: X,  position_y: Y * 3, tool_module_id: 'bank-to-csv' },
      { step_key: 's4',  title: 'Analyse invoices & receipts',      assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 90,  position_x: X,  position_y: Y * 4, tool_module_id: 'full-analysis' },
      { step_key: 's5',  title: 'Prepare accounts & SA supplementary', assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 90, position_x: X, position_y: Y * 5, tool_module_id: 'final-accounts' },
      { step_key: 's6',  title: 'Manager review',                   assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 45,  position_x: X,  position_y: Y * 6 },
      { step_key: 's7',  title: 'Send to client for approval',      assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 7 },
      { step_key: 'sr2', title: 'Send approval reminder to client', description: 'Client has not yet approved the accounts — send a reminder.',              assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 8 },
      { step_key: 's8',  title: 'Client approves accounts',         assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' },                             position_x: X,  position_y: Y * 9 },
      { step_key: 's9',  title: 'File self assessment return',      assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 30,  position_x: X,  position_y: Y * 10 },
      { step_key: 's10', title: 'Advise tax payment dates',         assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 11 },
    ],
    edges: [
      { from_step_key: 's1',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 5 }, ...TO },
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 'sr1', to_step_key: 's2',  condition_type: 'always',      ...BK },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's4',  to_step_key: 's5',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's5',  to_step_key: 's6',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's6',  to_step_key: 's7',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's7',  to_step_key: 'sr2', condition_type: 'timeout',     condition_config: { timeout_days: 5 }, ...TO },
      { from_step_key: 's7',  to_step_key: 's8',  condition_type: 'on_complete', ...VD },
      { from_step_key: 'sr2', to_step_key: 's8',  condition_type: 'always',      ...BK },
      { from_step_key: 's8',  to_step_key: 's9',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's9',  to_step_key: 's10', condition_type: 'on_complete', ...VD },
    ],
  },

  // ─── Self Assessment ─────────────────────────────────────────────────────────
  {
    id: 'default-self-assessment',
    name: 'Self Assessment Return',
    description: 'Individual self assessment tax return workflow.',
    category: 'self_assessment',
    recurrence_type: 'annually',
    estimated_duration_days: 21,
    steps: [
      { step_key: 's1',  title: 'Request personal income information', description: 'Employment income, dividends, interest, rental income, capital gains etc.', assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X,  position_y: 0 },
      { step_key: 'sr1', title: 'Send income information chaser',      description: 'Client has not yet provided their income details — send a chaser email.',  assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 1 },
      { step_key: 's2',  title: 'Client provides all income details',                                                                                            assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' },                             position_x: X,  position_y: Y * 2 },
      { step_key: 's3',  title: 'Process rental income & expenses',    description: 'If client has rental properties.',                                         assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 60, position_x: X, position_y: Y * 3, tool_module_id: 'landlord' },
      { step_key: 's4',  title: 'Prepare SA return',                                                                                                            assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 90, position_x: X,  position_y: Y * 4 },
      { step_key: 's5',  title: 'Manager review',                                                                                                               assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 30, position_x: X,  position_y: Y * 5 },
      { step_key: 's6',  title: 'Send to client for approval',                                                                                                  assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 6 },
      { step_key: 'sr2', title: 'Send approval reminder to client',    description: 'Client has not yet approved the SA return — send a reminder.',             assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 7 },
      { step_key: 's7',  title: 'Client approves return',                                                                                                       assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' },                             position_x: X,  position_y: Y * 8 },
      { step_key: 's8',  title: 'Submit to HMRC',                                                                                                               assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 20, position_x: X,  position_y: Y * 9 },
      { step_key: 's9',  title: 'Advise tax payment dates to client',                                                                                           assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 10 },
    ],
    edges: [
      { from_step_key: 's1',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 5 }, ...TO },
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 'sr1', to_step_key: 's2',  condition_type: 'always',      ...BK },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's4',  to_step_key: 's5',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's5',  to_step_key: 's6',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's6',  to_step_key: 'sr2', condition_type: 'timeout',     condition_config: { timeout_days: 5 }, ...TO },
      { from_step_key: 's6',  to_step_key: 's7',  condition_type: 'on_complete', ...VD },
      { from_step_key: 'sr2', to_step_key: 's7',  condition_type: 'always',      ...BK },
      { from_step_key: 's7',  to_step_key: 's8',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's8',  to_step_key: 's9',  condition_type: 'on_complete', ...VD },
    ],
  },

  // ─── Monthly Payroll ─────────────────────────────────────────────────────────
  {
    id: 'default-payroll-monthly',
    name: 'Payroll Run (Monthly)',
    description: 'Monthly payroll processing and RTI submission workflow.',
    category: 'payroll',
    recurrence_type: 'monthly',
    estimated_duration_days: 5,
    steps: [
      { step_key: 's0',  title: 'Request payroll information from client', description: 'Request hours, new starters, leavers, salary changes and bonuses for the month.', assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 10, position_x: X,  position_y: 0 },
      { step_key: 'sr1', title: 'Send payroll information chaser',         description: 'Client has not yet provided payroll information — send an urgent chaser.',         assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 1 },
      { step_key: 's1',  title: 'Receive payroll information from client',                                                                                                  assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' },                             position_x: X,  position_y: Y * 2 },
      { step_key: 's2',  title: 'Process payroll',                                                                                                                         assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 60, position_x: X, position_y: Y * 3 },
      { step_key: 's3',  title: 'Prepare P32 summary',                                                                                                                     assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 4, tool_module_id: 'p32' },
      { step_key: 's4',  title: 'Submit RTI to HMRC',                                                                                                                      assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 5 },
      { step_key: 's5',  title: 'Send payslips & P32 to client',                                                                                                           assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 6 },
    ],
    edges: [
      { from_step_key: 's0',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 2 }, ...TO },
      { from_step_key: 's0',  to_step_key: 's1',  condition_type: 'on_complete', ...VD },
      { from_step_key: 'sr1', to_step_key: 's1',  condition_type: 'always',      ...BK },
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's4',  to_step_key: 's5',  condition_type: 'on_complete', ...VD },
    ],
  },

  // ─── Bi-weekly Payroll ───────────────────────────────────────────────────────
  {
    id: 'default-payroll-biweekly',
    name: 'Payroll Run (Bi-weekly)',
    description: 'Bi-weekly payroll processing for clients on a fortnightly pay schedule.',
    category: 'payroll',
    recurrence_type: 'bi-weekly',
    estimated_duration_days: 3,
    steps: [
      { step_key: 's0',  title: 'Request payroll information from client', description: 'Request hours, any changes or new starters for this fortnight.',       assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 10, position_x: X,  position_y: 0 },
      { step_key: 'sr1', title: 'Send payroll information chaser',         description: 'Client has not yet provided payroll information — send an urgent chaser.', assignee_role: 'team_member', email_reminder_enabled: true, email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5, position_x: XR, position_y: Y * 1 },
      { step_key: 's1',  title: 'Receive payroll information from client',                                                                                       assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' },                             position_x: X,  position_y: Y * 2 },
      { step_key: 's2',  title: 'Process payroll',                                                                                                               assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 45, position_x: X, position_y: Y * 3 },
      { step_key: 's3',  title: 'Submit RTI to HMRC',                                                                                                           assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 4 },
      { step_key: 's4',  title: 'Send payslips to client',                                                                                                      assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 10, position_x: X, position_y: Y * 5 },
    ],
    edges: [
      { from_step_key: 's0',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 1 }, ...TO },
      { from_step_key: 's0',  to_step_key: 's1',  condition_type: 'on_complete', ...VD },
      { from_step_key: 'sr1', to_step_key: 's1',  condition_type: 'always',      ...BK },
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
    ],
  },

  // ─── Confirmation Statement ──────────────────────────────────────────────────
  {
    id: 'default-confirmation-statement',
    name: 'Confirmation Statement',
    description: 'Annual Companies House confirmation statement filing workflow.',
    category: 'companies_house',
    recurrence_type: 'annually',
    estimated_duration_days: 7,
    steps: [
      { step_key: 's1',  title: 'Check Companies House data',           description: 'Review current officer, PSC, and share capital information on CH.',    assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 20, position_x: X,  position_y: 0, tool_module_id: 'ch-secretarial' },
      { step_key: 's2',  title: 'Confirm details with client',                                                                                               assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X,  position_y: Y * 1 },
      { step_key: 'sr1', title: 'Send confirmation reminder to client', description: 'Client has not yet confirmed their Companies House details — send a chaser.', assignee_role: 'team_member', email_reminder_enabled: true, email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5, position_x: XR, position_y: Y * 2 },
      { step_key: 's3',  title: 'Client confirms all details correct',                                                                                       assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' },                             position_x: X,  position_y: Y * 3 },
      { step_key: 's4',  title: 'File confirmation statement',                                                                                               assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' }, time_estimate_minutes: 20, position_x: X,  position_y: Y * 4 },
      { step_key: 's5',  title: 'Advise client filing complete',                                                                                             assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 10, position_x: X,  position_y: Y * 5 },
    ],
    edges: [
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's2',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 3 }, ...TO },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 'sr1', to_step_key: 's3',  condition_type: 'always',      ...BK },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's4',  to_step_key: 's5',  condition_type: 'on_complete', ...VD },
    ],
  },

  // ─── Bookkeeping Review ──────────────────────────────────────────────────────
  {
    id: 'default-bookkeeping-review',
    name: 'Bookkeeping Review',
    description: 'Periodic bookkeeping review — suitable for monthly or quarterly management accounts clients.',
    category: 'bookkeeping',
    recurrence_type: 'monthly',
    estimated_duration_days: 7,
    steps: [
      { step_key: 's1',  title: 'Request documents from client',    assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X,  position_y: 0 },
      { step_key: 'sr1', title: 'Send document chaser to client',   description: 'Client has not yet provided their documents — send a chaser email.',       assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 5,  position_x: XR, position_y: Y * 1 },
      { step_key: 's2',  title: 'Client provides documents',        assignee_role: 'client',      email_reminder_enabled: false, email_reminder_config: { recipients: [],         timing: 'on_assign' },                             position_x: X,  position_y: Y * 2 },
      { step_key: 's3',  title: 'Process bank statements',          assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 30, position_x: X, position_y: Y * 3, tool_module_id: 'bank-to-csv' },
      { step_key: 's4',  title: 'Analyse invoices & receipts',      assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 60, position_x: X, position_y: Y * 4, tool_module_id: 'full-analysis' },
      { step_key: 's5',  title: 'Reconcile accounts',               assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 30, position_x: X, position_y: Y * 5 },
      { step_key: 's6',  title: 'Prepare management accounts',      assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 45, position_x: X, position_y: Y * 6, tool_module_id: 'performance' },
      { step_key: 's7',  title: 'Manager review',                   assignee_role: 'team_member', email_reminder_enabled: false, email_reminder_config: { recipients: [], timing: 'on_assign' }, time_estimate_minutes: 30, position_x: X, position_y: Y * 7 },
      { step_key: 's8',  title: 'Send report to client',            assignee_role: 'team_member', email_reminder_enabled: true,  email_reminder_config: { recipients: ['client'], timing: 'on_assign' }, time_estimate_minutes: 15, position_x: X, position_y: Y * 8 },
    ],
    edges: [
      { from_step_key: 's1',  to_step_key: 'sr1', condition_type: 'timeout',     condition_config: { timeout_days: 3 }, ...TO },
      { from_step_key: 's1',  to_step_key: 's2',  condition_type: 'on_complete', ...VD },
      { from_step_key: 'sr1', to_step_key: 's2',  condition_type: 'always',      ...BK },
      { from_step_key: 's2',  to_step_key: 's3',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's3',  to_step_key: 's4',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's4',  to_step_key: 's5',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's5',  to_step_key: 's6',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's6',  to_step_key: 's7',  condition_type: 'on_complete', ...VD },
      { from_step_key: 's7',  to_step_key: 's8',  condition_type: 'on_complete', ...VD },
    ],
  },
];

export const TEMPLATE_CATEGORY_LABELS: Record<string, string> = {
  vat: 'VAT',
  year_end: 'Year End',
  self_assessment: 'Self Assessment',
  payroll: 'Payroll',
  companies_house: 'Companies House',
  bookkeeping: 'Bookkeeping',
  general: 'General',
};
