-- MTD IT — client-approval cycles for each quarter.
--
-- One row per Send-to-client event. We keep history (don't UPDATE in place
-- when resending) so the audit trail is complete: when each version of the
-- pack was sent, who clicked Approve, when, from where.
--
-- Status flow on mtd_it_quarters is driven by the latest row here:
--     none yet         → quarter.status = 'complete' (or earlier)
--     row exists       → quarter.status = 'sent'
--     row.approved_at  → quarter.status = 'approved'
-- Quarters can be edited after approval; the active approval row gets
-- edited_since_approved_at stamped so the dashboard can flag it.

create table if not exists public.mtd_it_quarter_approvals (
  id                        uuid primary key default gen_random_uuid(),
  quarter_id                uuid not null references public.mtd_it_quarters(id) on delete cascade,

  -- Public access token used in /mtd-it/approve/[token]. Random ~32 chars,
  -- generated by the API. NOT a JWT — just an opaque string.
  token                     text not null unique,

  -- Who triggered Send-to-client + when.
  sent_by                   uuid references public.users(id) on delete set null,
  sent_at                   timestamptz not null default now(),
  expires_at                timestamptz not null default (now() + interval '30 days'),
  recipient_email           text not null,
  cover_note                text,

  -- Approval state. Exactly one of approved_at / changes_requested_at is set
  -- once the client has responded. Both null while pending.
  approved_at               timestamptz,
  changes_requested_at      timestamptz,
  changes_note              text,

  -- Audit on the client's click (filled by the public POST endpoint)
  responded_ip              text,
  responded_user_agent      text,

  -- Reminder tracking
  reminder_count            int  not null default 0,
  last_reminder_at          timestamptz,

  -- Set true when a previous approval is superseded by a new Send. Lets us
  -- keep history while knowing which row is "active" at any moment.
  voided_at                 timestamptz,

  -- Bumped whenever any entry / setting on the quarter changes after the
  -- client has approved. Powers the "approved but edited" dashboard flag.
  edited_since_approved_at  timestamptz,

  created_at                timestamptz not null default now()
);

create index if not exists mtd_it_quarter_approvals_quarter_idx on public.mtd_it_quarter_approvals(quarter_id);
create unique index if not exists mtd_it_quarter_approvals_token_idx on public.mtd_it_quarter_approvals(token);

alter table public.mtd_it_quarter_approvals enable row level security;

-- Firm members can read + manage approvals for their firm's quarters.
create policy "firm_access_mtd_it_quarter_approvals"
  on public.mtd_it_quarter_approvals for all
  using (quarter_id in (
    select id from public.mtd_it_quarters
    where client_id in (
      select id from public.clients
      where firm_id in (select firm_id from public.users where id = auth.uid())
    )
  ));

-- The public approval page reads + writes through service-role (bypasses
-- RLS) so we deliberately do NOT add a public/anon policy.
